# Generated by Django 2.2.5 on 2019-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FURNITURE', 'Furniture'), ('TEXTBOOKS', 'Textbooks'), ('HOUSING', 'Housing'), ('SERVICES', 'Services'), ('GIGS', 'Gigs'), ('LOST_AND_FOUND', 'Lost & Found'), ('OTHER', 'Other')], max_length=15)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OPEN_BOX', 'Open Box'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished'), ('FOR_PARTS', 'For Parts or Not Working')], max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
