# Generated by Django 2.2.5 on 2019-11-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(default='0000', max_length=50),
        ),
    ]
