# Generated by Django 2.2.5 on 2019-10-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0002_auto_20190930_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateListing',
            new_name='Listing',
        ),
    ]
