# Generated by Django 2.2.5 on 2019-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0002_listing_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='posted',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
