# Generated by Django 2.2.5 on 2019-11-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0003_auto_20191110_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191110164547240310', max_length=50),
        ),
    ]
