# Generated by Django 2.2.5 on 2019-11-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0004_auto_20191026_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
    ]
