# Generated by Django 2.2.5 on 2019-11-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0004_auto_20191110_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191110185605870870', max_length=50),
        ),
    ]
