# Generated by Django 2.2.5 on 2019-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0004_auto_20191110_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageurl',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191110200641148208', max_length=50),
        ),
    ]
