# Generated by Django 2.2.5 on 2019-11-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0005_auto_20191110_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imageurl',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191110201813049176', max_length=50),
        ),
    ]
