# Generated by Django 2.2.5 on 2019-11-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0006_auto_20191110_2018'),
        ('craigslist', '0005_auto_20191110_1856'),
    ]

    operations = [
    ]
