# Generated by Django 2.2.5 on 2019-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0006_auto_20191104_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
