# Generated by Django 2.2.5 on 2019-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0006_auto_20191031_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='2019-11-02 15:19:14.134323', max_length=50),
        ),
    ]
