# Generated by Django 2.2.5 on 2019-11-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0007_merge_20191111_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191111001711279732', max_length=50),
        ),
    ]
