# Generated by Django 2.2.5 on 2019-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0007_auto_20191104_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
