# Generated by Django 2.2.5 on 2019-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0007_listing_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='2019110215:26:56.360721', max_length=50),
        ),
    ]
