# Generated by Django 2.2.5 on 2019-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0008_auto_20191111_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191111002457392836', max_length=50),
        ),
    ]
