# Generated by Django 2.2.5 on 2019-11-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0008_auto_20191102_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='2019110218:43:54.169200', max_length=50),
        ),
    ]
