# Generated by Django 2.2.5 on 2019-11-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0009_auto_20191111_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191111002822296895', max_length=50),
        ),
    ]
