# Generated by Django 2.2.5 on 2019-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0009_auto_20191102_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191102185912583398', max_length=50),
        ),
    ]
