# Generated by Django 2.2.5 on 2019-11-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0008_auto_20191104_1506'),
        ('craigslist', '0010_auto_20191102_1859'),
    ]

    operations = [
    ]
