# Generated by Django 2.2.5 on 2019-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0010_auto_20191102_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191109124003952794', max_length=50),
        ),
    ]
