# Generated by Django 2.2.5 on 2019-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0011_auto_20191109_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='20191110133608951898', max_length=50),
        ),
    ]
